### ISSUE TITLE
Laconic Doc Website Updates

### ISSUE THREAD

**Issue by olive-kimoto** [LaconicNetwork/docs.laconic.com#84]
- [ ] Remove "Home" from navigation (it's redundant)
- [ ] Add "Laconic.com" to navigation (Route to https://www.laconic.com/) as the last navigation item
- [ ] Add a card for Twitter to Community page (Use lorem ipsum for copy for now). Make it the 3rd card.
- [ ] Add Linkedin to footer

**Comment by zramsay** [comment]
these are all complete in the current version
