### ISSUE TITLE
README.md Focus: Global Index vs How to Edit/Add

### ISSUE THREAD

**Issue by rickmanelius** [LaconicNetwork/docs.laconic.com#90]
IMHO, a good, global docs README.md should start with an index and link out to all sub-docs.

Right now it's primarily focused on how to contribute, which is an important activity that can be tucked away to a subpage.

**Comment by zramsay** [comment]
see #91

**Comment by zramsay** [comment]
i think this repo would rarely be accessed by developers readings docs, instead they'll use docs.laconic.com

Then the repos that developers might actually be in and using will have awesome (but simple) READMEs with links to relevant docs pages

**Comment by zramsay** [comment]
moot
